# Generated by Django 6.0.3 on 2026-04-08 04:51

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_prompt', models.TextField(help_text='Petición del usuario')),
                ('contexto', models.TextField(help_text='Contexto RAG enviado a la IA')),
                ('respuesta_ia', models.TextField(help_text='Respuesta cruda de la IA')),
                ('acciones_ejecutadas', models.TextField(blank=True, help_text='Acciones JSON o resumen de las operacines de backend', null=True)),
                ('exitosa', models.BooleanField(default=True, help_text='Indica si la operación finalizó sin excepciones u errores de red')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto (recibos, comprobantes, excel, etc.)', null=True, upload_to='interacciones/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'csv', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('nombre_archivo_original', models.CharField(blank=True, help_text='Nombre original del archivo para referencia', max_length=255)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
