# Generated by Django 6.0.3 on 2026-04-08 04:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('SOCIO', 'Socio'), ('INTERNO', 'Interno'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', help_text='Rol del usuario en el sistema', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección física del usuario', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema')),
                ('activo_comercialmente', models.BooleanField(default=True, help_text='Indica si el usuario está activo para operaciones comerciales')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'tbl_usuarios',
                'ordering': ['-fecha_registro'],
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_anticipo', models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de anticipo acordado para apartados (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, help_text='Límite de crédito disponible para el socio', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo pendiente de pago', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento_especial', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento especial acordado (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas sobre el socio (solo visible para internos/admins)', null=True)),
                ('fecha_acuerdo', models.DateField(auto_now_add=True, help_text='Fecha del acuerdo comercial')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el perfil de socio está activo')),
                ('usuario', models.OneToOneField(help_text='Usuario asociado al perfil de socio', limit_choices_to={'rol': 'SOCIO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Socio',
                'verbose_name_plural': 'Perfiles de Socios',
                'db_table': 'tbl_perfiles_socio',
                'managed': True,
            },
        ),
    ]
