# Generated by Django 6.0.3 on 2026-04-10 15:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(blank=True, help_text='Identificador fiscal del cliente', max_length=20, null=True, unique=True)),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre comercial o razón social', max_length=200)),
                ('fecha_afiliacion', models.DateField(auto_now_add=True, help_text='Fecha de afiliación como cliente')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', help_text='Estado operativo del cliente', max_length=20)),
                ('usuario', models.OneToOneField(help_text='Usuario asociado a la entidad de negocio cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'tbl_clientes',
                'ordering': ['-fecha_afiliacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(help_text='Número único de empleado', max_length=20, unique=True)),
                ('departamento', models.CharField(blank=True, help_text='Área o departamento del empleado', max_length=100)),
                ('fecha_contratacion', models.DateField(auto_now_add=True, help_text='Fecha de contratación')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, help_text='Salario base del empleado', max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'Licencia'), ('INACTIVO', 'Inactivo')], default='ACTIVO', help_text='Estado laboral del empleado', max_length=20)),
                ('usuario', models.OneToOneField(help_text='Usuario asociado a la entidad de negocio empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'tbl_empleados',
                'ordering': ['-fecha_contratacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_anticipo', models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de anticipo acordado para apartados (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, help_text='Límite de crédito disponible para el socio', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo pendiente de pago', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento_especial', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento especial acordado (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas sobre el socio (solo visible para internos/admins)', null=True)),
                ('fecha_acuerdo', models.DateField(auto_now_add=True, help_text='Fecha del acuerdo comercial')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el perfil de socio está activo')),
                ('usuario', models.OneToOneField(help_text='Usuario asociado a la entidad de negocio socio', on_delete=django.db.models.deletion.CASCADE, related_name='socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'tbl_socios',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='PerfilSocio',
        ),
    ]
