"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from pathlib import Path
import environ  # necesitas instalar django-environ
import sys

# Inicializa environ
env = environ.Env(
    DEBUG=(bool, False),
    DB_ENGINE=(str, 'sqlite'),  # por defecto SQLite para desarrollo simple
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Lee el archivo .env si existe
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Intentar leer .env en la raíz del repo, pero no es obligatorio
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))

SECRET_KEY = env('SECRET_KEY', default='django-insecure-clave-temporal-para-eft-backend-2026')
DEBUG = env('DEBUG', default=False)

# Configuración de base de datos
DB_ENGINE = env('DB_ENGINE')

if DB_ENGINE == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('POSTGRES_DB', default='miproyecto'),
            'USER': env('POSTGRES_USER', default='postgres'),
            'PASSWORD': env('POSTGRES_PASSWORD', default='postgres'),
            'HOST': env('POSTGRES_HOST', default='db'),  # ¡importante!
            'PORT': env('POSTGRES_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '10.0.2.2', '0.0.0.0'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Terceros
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Apps propias
    'users',
    'locations',
    'products',
    'orders',
    'payments',
    'shipping',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'bold_webhook': '100/min',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
}

# CORS (permitir todo en desarrollo)
CORS_ALLOW_ALL_ORIGINS = True

def _env_fallback(*keys, default=''):
    for key in keys:
        value = env(key, default='')
        if value:
            return value
    return default


BOLD_INTEGRITY_SECRET = _env_fallback(
    'BOLD_INTEGRITY_SECRET',
    'LLAVE_SECRETA_BOLD_PRUEBA',
    'LLAVE_SECRETA_BOLD_PROD',
)
BOLD_PUBLIC_KEY = _env_fallback(
    'BOLD_PUBLIC_KEY',
    'LLAVE_IDENTIDAD_BOLD_PRUEBA',
    'LLAVE_IDENTIDAD_BOLD_PROD',
)
BOLD_REDIRECT_URL = env('BOLD_REDIRECT_URL', default='')
BOLD_CHECKOUT_URL = env('BOLD_CHECKOUT_URL', default='')

SKYDROPX_API_KEY_SANDBOX = env('API_KEY_SKYDROPX_SANDBOX', default='')
SKYDROPX_API_KEY_PROD = env('API_KEY_SKYDROPX', default='')
SKYDROPX_API_BASE_URL = env('SKYDROPX_API_BASE_URL', default='')

# Select credentials based on explicit URL override, then fall back to whichever key is set.
# If SKYDROPX_API_BASE_URL points to production (or is not sandbox), use production keys.
_use_sandbox = (
    'sb-pro' in SKYDROPX_API_BASE_URL
    if SKYDROPX_API_BASE_URL
    else bool(SKYDROPX_API_KEY_SANDBOX and not SKYDROPX_API_KEY_PROD)
)

if not SKYDROPX_API_BASE_URL:
    SKYDROPX_API_BASE_URL = (
        'https://sb-pro.skydropx.com/api/v1' if _use_sandbox
        else 'https://pro.skydropx.com/api/v1'
    )

SKYDROPX_CLIENT_ID = _env_fallback(
    'SKYDROPX_CLIENT_ID',
    'API_KEY_SKYDROPX_SANDBOX' if _use_sandbox else 'API_KEY_SKYDROPX',
    'API_KEY_SKYDROPX' if _use_sandbox else 'API_KEY_SKYDROPX_SANDBOX',
)
SKYDROPX_CLIENT_SECRET = _env_fallback(
    'SKYDROPX_CLIENT_SECRET',
    'API_SECRET_KEY_SKYDROPX_SANDBOX' if _use_sandbox else 'API_SECRET_KEY_SKYDROPX',
    'API_SECRET_KEY_SKYDROPX' if _use_sandbox else 'API_SECRET_KEY_SKYDROPX_SANDBOX',
)
SKYDROPX_API_KEY = SKYDROPX_CLIENT_ID  # alias
SKYDROPX_ORIGIN_POSTAL_CODE = env('SKYDROPX_ORIGIN_POSTAL_CODE', default='')
SHIPPING_CARRIERS = env.list('SHIPPING_CARRIERS', default=[])
SHIPPING_ORIGIN_NAME = env('SHIPPING_ORIGIN_NAME', default='')
SHIPPING_ORIGIN_ADDRESS = env('SHIPPING_ORIGIN_ADDRESS', default='')
SHIPPING_ORIGIN_CITY = env('SHIPPING_ORIGIN_CITY', default='')
SHIPPING_ORIGIN_STATE = env('SHIPPING_ORIGIN_STATE', default='')
SHIPPING_ORIGIN_COUNTRY = env('SHIPPING_ORIGIN_COUNTRY', default='CO')
SHIPPING_ORIGIN_PHONE = env('SHIPPING_ORIGIN_PHONE', default='')
SHIPPING_ORIGIN_EMAIL = env('SHIPPING_ORIGIN_EMAIL', default='')
SHIPPING_DESTINATION_COUNTRY = env('SHIPPING_DESTINATION_COUNTRY', default='CO')

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=CELERY_BROKER_URL)
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=False)
CELERY_TASK_EAGER_PROPAGATES = env.bool('CELERY_TASK_EAGER_PROPAGATES', default=True)
CELERY_TIMEZONE = TIME_ZONE

if 'test' in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    if not BOLD_INTEGRITY_SECRET:
        BOLD_INTEGRITY_SECRET = 'test-secret'
