# Generated by Django 6.0.3 on 2026-04-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiUsuarios', '0002_remove_usuario_rol_cliente_empleado_socio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('propietario_permitido', models.CharField(choices=[('EMPRESA', 'Empresa'), ('EMPLEADO', 'Empleado'), ('CLIENTE', 'Cliente'), ('SOCIO', 'Socio'), ('UNIVERSAL', 'Universal')], default='UNIVERSAL', max_length=20)),
                ('requiere_vencimiento', models.BooleanField(default=False)),
                ('dias_alerta_vencimiento', models.PositiveIntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_tipos_documento',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('titulo', models.CharField(max_length=220)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('ultima_version', models.PositiveIntegerField(default=1)),
                ('archivo_actual', models.FileField(upload_to='documentos/actual/')),
                ('hash_contenido', models.CharField(blank=True, max_length=128)),
                ('propietario_empresa', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propietario_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='apiUsuarios.cliente')),
                ('propietario_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='apiUsuarios.empleado')),
                ('propietario_socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='apiUsuarios.socio')),
                ('usuario_actualizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='apiDocumentos.tipodocumento')),
            ],
            options={
                'db_table': 'tbl_documentos',
                'ordering': ['-fecha_actualizacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('archivo', models.FileField(upload_to='documentos/versiones/')),
                ('hash_contenido', models.CharField(blank=True, max_length=128)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='apiDocumentos.documento')),
                ('usuario_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_documento_editadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_versiones_documento',
                'ordering': ['-numero_version', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccesoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('VISUALIZACION', 'Visualizacion'), ('DESCARGA', 'Descarga')], max_length=20)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos_documento', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='apiDocumentos.documento')),
                ('version_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='apiDocumentos.versiondocumento')),
            ],
            options={
                'db_table': 'tbl_accesos_documento',
                'ordering': ['-fecha_evento'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='versiondocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'numero_version'), name='uniq_documento_numero_version'),
        ),
        migrations.AddIndex(
            model_name='accesodocumento',
            index=models.Index(fields=['documento', '-fecha_evento'], name='tbl_accesos_documen_14918b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesodocumento',
            index=models.Index(fields=['usuario', '-fecha_evento'], name='tbl_accesos_usuario_4e4485_idx'),
        ),
    ]
