# Generated by Django 4.2.30 on 2026-05-24 21:44

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('label_url', models.URLField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estimated_days', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('package_type', models.CharField(choices=[('box', 'Box'), ('merchandise', 'Merchandise')], default='box', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='pending', max_length=30)),
                ('skydropx_shipment_id', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('carrier', models.CharField(max_length=120)),
                ('service', models.CharField(blank=True, max_length=120)),
                ('service_code', models.CharField(blank=True, max_length=120)),
                ('estimated_days', models.PositiveIntegerField(default=0)),
                ('cost_cop', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('skydropx_quote_id', models.CharField(blank=True, max_length=120)),
                ('destination_city', models.CharField(max_length=120)),
                ('destination_postal_code', models.CharField(blank=True, max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('shipping_credit_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
