# Generated by Django 4.2.30 on 2026-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingquote',
            name='skydropx_quotation_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='skydropx_rate_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
