# Generated by Django 4.2.30 on 2026-05-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_add_skydropx_quotation_rate_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre / Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=120, verbose_name='Ciudad (area_level2/3)')),
                ('state', models.CharField(max_length=120, verbose_name='Departamento (area_level1)')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('country_code', models.CharField(default='CO', max_length=5, verbose_name='Código de país')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Origen de envío',
                'verbose_name_plural': 'Origen de envío',
            },
        ),
    ]
