# Generated by Django 6.0.3 on 2026-04-10 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('metodo_http', models.CharField(max_length=10)),
                ('accion', models.CharField(max_length=80)),
                ('recurso', models.CharField(max_length=80)),
                ('resultado', models.CharField(choices=[('SUCCESS', 'Success'), ('FORBIDDEN', 'Forbidden'), ('ERROR', 'Error')], max_length=20)),
                ('codigo_estado', models.PositiveSmallIntegerField()),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_eventos_auditoria',
                'ordering': ['-fecha_evento'],
                'managed': True,
                'indexes': [models.Index(fields=['-fecha_evento'], name='tbl_eventos_fecha_e_78d3de_idx'), models.Index(fields=['recurso', 'accion', '-fecha_evento'], name='tbl_eventos_recurso_a7d6e9_idx'), models.Index(fields=['usuario', '-fecha_evento'], name='tbl_eventos_usuario_120bab_idx'), models.Index(fields=['resultado', '-fecha_evento'], name='tbl_eventos_resulta_b23859_idx')],
            },
        ),
    ]
