# Generated by Django 6.0.3 on 2026-04-08 04:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiInventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA_CLIENTE', 'Venta a Cliente'), ('RE_STOCK', 'Reabastecimiento'), ('APARTADO_SOCIO', 'Apartado de Socio')], help_text='Tipo de pedido', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('PAGADO_PARCIAL', 'Pago Parcial'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', help_text='Estado actual del pedido', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total del pedido (calculado automáticamente)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto ya pagado del pedido', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento aplicado', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pedido', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del pedido')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del pedido')),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Fecha en que se completó el pedido', null=True)),
                ('cliente', models.ForeignKey(help_text='Cliente o proveedor asociado al pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('interno_asignado', models.ForeignKey(blank=True, help_text='Usuario interno/admin asignado al pedido', limit_choices_to={'rol__in': ['INTERNO', 'ADMINISTRADOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'tbl_pedidos',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de unidades del producto', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento del pedido (histórico)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de impuesto al momento del pedido', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True, help_text='Notas específicas del producto en este pedido', null=True)),
                ('producto', models.ForeignKey(help_text='Producto incluido en el pedido', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='apiInventario.producto')),
                ('pedido', models.ForeignKey(help_text='Pedido al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='apiPedidos.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'tbl_detalles_pedido',
                'managed': True,
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
