# Generated by Django 6.0.3 on 2026-04-10 15:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiPedidos', '0001_initial'),
        ('apiUbicaciones', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='porcentaje_impuesto',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='monto_impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de impuesto del detalle al momento del pedido', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubicacion_entrega',
            field=models.ForeignKey(blank=True, help_text='Ubicación de entrega del pedido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_entrega', to='apiUbicaciones.ubicacion'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='interno_asignado',
            field=models.ForeignKey(blank=True, help_text='Usuario interno/admin asignado al pedido', limit_choices_to=models.Q(('empleado__isnull', False)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
