# Generated by Django 6.0.4 on 2026-04-13 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_dane', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_departamentos',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_dane', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiUbicaciones.departamento')),
            ],
            options={
                'db_table': 'tbl_municipios',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('street', models.TextField()),
                ('country', models.CharField(default='CO', max_length=2)),
                ('postalCode', models.CharField(blank=True, help_text='Postal code', max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiUbicaciones.municipio')),
            ],
        ),
    ]
