# Generated by Django 6.0.3 on 2026-04-08 04:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('sku', models.CharField(help_text='Código SKU único del producto', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del producto', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de impuesto aplicable (ej: 16.00 para IVA 16%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad actual en inventario', validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.IntegerField(default=0, help_text='Stock mínimo antes de requerir reabastecimiento', validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está activo para la venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del producto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del producto')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'tbl_productos',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], help_text='Tipo de movimiento', max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad de unidades movidas', validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_anterior', models.IntegerField(help_text='Stock antes del movimiento')),
                ('stock_nuevo', models.IntegerField(help_text='Stock después del movimiento')),
                ('motivo', models.TextField(blank=True, help_text='Motivo o descripción del movimiento', null=True)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia (ej: número de pedido, factura)', max_length=100, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento')),
                ('usuario', models.ForeignKey(help_text='Usuario interno/administrador que procesó el movimiento', limit_choices_to={'rol__in': ['INTERNO', 'ADMINISTRADOR']}, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(help_text='Producto afectado por el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='apiInventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'tbl_movimientos_inventario',
                'ordering': ['-fecha_movimiento'],
                'managed': True,
            },
        ),
    ]
