# Generated by Django 6.0.3 on 2026-04-10 15:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiInventario', '0001_initial'),
        ('apiUbicaciones', '__first__'),
        ('apiUsuarios', '0002_remove_usuario_rol_cliente_empleado_socio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vida_util_meses', models.PositiveIntegerField(default=60, help_text='Vida útil estimada en meses para depreciación lineal.', validators=[django.core.validators.MinValueValidator(1)])),
                ('tasa_depreciacion_anual', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje anual referencial.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Activo',
                'verbose_name_plural': 'Categorias de Activo',
                'db_table': 'tbl_categorias_activo',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='porcentaje_impuesto',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario interno/administrador que procesó el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_activo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('VEHICULO', 'Vehiculo'), ('EQUIPO', 'Equipo'), ('COMPUTADOR', 'Computador'), ('OTRO', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('INACTIVO', 'Inactivo'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=30)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_adquisicion', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to='apiUsuarios.empleado')),
                ('asignado_a_ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to='apiUbicaciones.ubicacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='apiInventario.categoriaactivo')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'db_table': 'tbl_activos_fijos',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MantenimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('descripcion', models.TextField()),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('alerta_vencida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='apiInventario.activofijo')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Activo',
                'verbose_name_plural': 'Mantenimientos de Activo',
                'db_table': 'tbl_mantenimientos_activo',
                'ordering': ['fecha_programada', 'id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Asignacion'), ('REASIGNACION', 'Reasignacion'), ('TRASLADO', 'Traslado'), ('MANTENIMIENTO', 'Mantenimiento'), ('BAJA', 'Baja')], max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='apiInventario.activofijo')),
                ('responsable_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_activo_como_anterior', to='apiUsuarios.empleado')),
                ('responsable_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_activo_como_nuevo', to='apiUsuarios.empleado')),
                ('ubicacion_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_activo_como_ubicacion_anterior', to='apiUbicaciones.ubicacion')),
                ('ubicacion_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_activo_como_ubicacion_nueva', to='apiUbicaciones.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Activo',
                'verbose_name_plural': 'Movimientos de Activo',
                'db_table': 'tbl_movimientos_activo',
                'ordering': ['-fecha_movimiento', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DepreciacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(choices=[('LINEAL', 'Lineal')], default='LINEAL', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_en_libros', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='apiInventario.activofijo')),
            ],
            options={
                'verbose_name': 'Depreciacion de Activo',
                'verbose_name_plural': 'Depreciaciones de Activo',
                'db_table': 'tbl_depreciaciones_activo',
                'ordering': ['-fecha', '-id'],
                'managed': True,
                'unique_together': {('activo', 'fecha')},
            },
        ),
    ]
