# Generated by Django 6.0.3 on 2026-04-08 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiCuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('egreso', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=32)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_proximo_intento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTADA', 'Ejecutada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('frecuencia', models.CharField(choices=[('UNICA', 'Única'), ('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='UNICA', max_length=20)),
                ('fecha_ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_repeticion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='apiTransacciones.categoria')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='apiCuentas.cuenta')),
            ],
            options={
                'db_table': 'tbl_programaciones_transacciones',
                'ordering': ['-fecha_programada'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=32)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_ejecucion', models.DateTimeField(null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='apiTransacciones.categoria')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='apiCuentas.cuenta')),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_generadas', to='apiTransacciones.programaciontransaccion')),
            ],
            options={
                'db_table': 'tbl_transacciones',
                'managed': True,
            },
        ),
    ]
