# Generated by Django 6.0.3 on 2026-04-08 05:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTransacciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True, 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('COSTO', 'Costo Operativo'), ('VENTA', 'Venta/Ingreso'), ('NOMINA', 'Nómina'), ('IMPUESTOS', 'Impuestos'), ('GENERAL', 'General')], default='GENERAL', help_text='Tipo de categoría empresarial', max_length=20),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='documento',
            field=models.FileField(blank=True, help_text='Documento fiscal o recibo relacionado (PDF, imagen, etc.)', null=True, upload_to='documentos_fiscales/'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='tbl_categorias',
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, help_text='Salario base del empleado', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('periodicidad', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', help_text='Periodicidad de pago', max_length=20)),
                ('bonos', models.DecimalField(decimal_places=2, default=0.0, help_text='Bonos adicionales', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deducciones', models.DecimalField(decimal_places=2, default=0.0, help_text='Deducciones (impuestos, préstamos, etc.)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('periodo_inicio', models.DateField(help_text='Fecha de inicio del periodo de pago')),
                ('periodo_fin', models.DateField(help_text='Fecha de fin del periodo de pago')),
                ('fecha_pago_programada', models.DateField(help_text='Fecha programada de pago')),
                ('fecha_pago_efectiva', models.DateField(blank=True, help_text='Fecha en que se realizó el pago efectivamente', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('RETRASADO', 'Retrasado')], default='PENDIENTE', help_text='Estado del pago de nómina', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre esta nómina', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Administrador que aprobó el pago', limit_choices_to={'rol': 'ADMINISTRADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(help_text='Empleado al que pertenece esta nómina', limit_choices_to={'rol__in': ['INTERNO', 'ADMINISTRADOR']}, on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'tbl_nominas',
                'ordering': ['-fecha_pago_programada'],
                'managed': True,
                'unique_together': {('empleado', 'periodo_inicio', 'periodo_fin')},
            },
        ),
    ]
