# Generated by Django 6.0.3 on 2026-04-10 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTransacciones', '0002_alter_categoria_options_categoria_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Administrador que aprobó el pago', limit_choices_to=models.Q(('is_superuser', True), ('groups__name', 'ADMIN_GENERAL'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(help_text='Empleado al que pertenece esta nómina', limit_choices_to=models.Q(('empleado__isnull', False)), on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to=settings.AUTH_USER_MODEL),
        ),
    ]
